version: "3.8"
services:

  # Backend
  backend:
    container_name: backend
    depends_on:
      - database
    build:
      context: .
      dockerfile: ./docker/services/backend/Dockerfile
    volumes:
      - ./backend:/var/www/backend
      - ./backend/composer.json:/var/www/backend/composer.json

  # Frontend
  frontend:
    tty: true
#    image: node:alpine
    container_name: frontend
    build:
      dockerfile: ./docker/services/frontend/Dockerfile
    volumes:
      - ./frontend:/var/www/frontend
      - /var/www/frontend/node_modules
    ports:
      - "8080:8000"


  # Web Server
  nginx:
    container_name: web
    image: nginx:alpine
    build:
      context: ./docker/services/web
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "3000:80"
    depends_on:
      - backend

  # Database
  database:
    container_name: db
    image: mysql:8.0.25
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"

#networks:
#  internal:
#    driver: bridge